package:
  name: testsystems_uibcdf
  # version: {{ GIT_DESCRIBE_TAG }}
  version: 0.0.0

source:
  path: ../../

build:
  # number: {{ GIT_DESCRIBE_NUMBER }}
  number: 0

requirements:
  build:
    - python
    # - cython
    # - setuptools

  run:
    - python
    - numpy
    - mdtraj
    - nglview
    - openmmtools
    - openmm
    - pdbfixer

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides the set of common molecular system used in the uibcdf lab for methods testing and projects development.
  dev_url: https://github.com/uibcdf/TestSystems_uibcdf
  doc_url: https://uibcdf.org
